import 'server-only';
import type { ManualContent } from '../user-manual';
export const adminManual:ManualContent={title:'Admin manual',intro:'Set up the workspace, maintain reporting lines, and review delivery issues. Administration and this manual require duty_time_admin: true on your Firebase account.',sections:[
{id:'setup',title:'1. Complete setup before users start',steps:['Review every station under Administration → Stations. Set its correct time zone and availability. Unconfigured stations fall back to Africa/Nairobi.','Add Maintenance and Operations contacts for each station, including working email addresses. Phone numbers are directory details; alerts are sent by email.','Create or enable your users, mark the appropriate people as line managers, and assign each user’s reporting managers.','Under Settings, choose whether manual check-in/check-out times are allowed and save additional duty/rest alert recipients.','With designated accounts, verify a real check-in, checkout, and email delivery before rolling out to the whole team.']},
{id:'users',title:'2. Add users and assign managers',steps:['Open Administration → Users → Add user. Enter first and last names, email, department, position, and an initial password of at least 12 characters.','Enable This user is a line manager for people who review their assigned team. Save their manager role before assigning them to others.','Open each user, select their line manager(s), and save. Having an admin role does not automatically make someone a reporting manager.','To suspend access, untick Enable DutyTime access and save. Reactivate by ticking it again. Existing duty history is retained; no Delete user action is available.','Use Export CSV to download all users with first name, last name, email, and assigned managers.','Use Change shared account password only when required: it affects the connected Firebase apps and signs out existing sessions.'],note:'The interface does not grant the duty_time_admin custom claim. Admin access is managed separately by an authorized Firebase administrator. Deactivating a DutyTime user does not delete their shared account or settle an open duty session; review that session separately.'},
{id:'stations',title:'3. Configure stations',steps:['Open Administration → Stations → Add station, or select an existing station to open its bottom sheet.','Set the station name and country. Use the searchable time zone picker to choose its actual local zone; for example, Nairobi uses Africa/Nairobi and Aweil uses Africa/Juba.','Leave Available for check-in selected for active stations. Untick it and save to deactivate a station; tick it to reactivate. The station and historical duty records remain stored.','Save a new station before adding its contacts. Zone changes apply to future sessions; existing sessions retain their saved zone.'],note:'Deactivating a station prevents new selections. It does not remove historical records or automatically close existing duty.'},
{id:'contacts',title:'4. Maintain station contacts',steps:['In the station bottom sheet, use Add contact to enter a contact name/department, email, and/or phone. Use Maintenance or Operations for automatic station alerts.','Use the contact card’s Edit button to update details.','Choose Deactivate when a contact should no longer be automatically notified. Its details remain visible as Inactive, and Reactivate restores it. There is no Delete contact action.','Inactive contacts are excluded from automatic station recipients and from search suggestions. If their email was also explicitly saved as an additional alert recipient, remove that selected address separately.']},
{id:'cutoffs',title:'5. Set automatic checkout times',steps:['The default is 7pm in the checked-in station’s local time. To override it, open an existing user under Administration → Users → Automatic checkout & lockout.','Untick Use the system default, select the desired local clock time, and Save cutoff. Assigned line managers can also do this from My line duty → select user.','The new cutoff applies to an open session. It cannot be earlier than that session’s check-in. A cutoff already reached can cause immediate automatic checkout.','Automatic checkout remains Pending actual checkout until the user or authorized reviewer supplies the true finish time.']},
{id:'alerts',title:'6. Configure duty and rest alerts',steps:['Under Administration → Settings, search for users or station contacts and select multiple recipients. You can also type an email and press Enter or Add email.','Remove unwanted recipient tags, then Save alert recipients. These additional recipients receive both over-12-hour duty alerts and denied next-day rest alerts.','Assigned line managers are included automatically. Maintenance and Operations contacts are included for stations represented in the overtime record, or the station selected for a denied rest check-in.','Duplicate addresses receive one email. Ordinary manual checkout reports go to line managers; automatic checkout and actual-time corrections also notify the user.'],note:'The daily threshold is 12 hours and the next-day rest requirement is eight hours. These are current system rules, not editable settings in this screen. The cutoff is a separate rule.'},
{id:'review',title:'7. Review records and delivery',steps:['Assigned managers use My line duty to review calendars, approve/reject missed entries, and correct sessions with a reason. Administrators have company-scoped review permissions; self-approval is not allowed.','Under Administration → Reports, inspect queued, failed, or blocked reports. No eligible recipients usually means reporting managers and/or contact emails need configuration.','Correct the recipient configuration and select Retry. A sent status means Resend accepted the message; it does not confirm inbox delivery.','For a pending automatic checkout, request the actual finish time rather than treating the cutoff as confirmed duty.']},
{id:'daily-checklist',title:'8. Ongoing admin checklist',steps:['Keep manager assignments and station contacts current when staff or responsibilities change.','Check each station’s time zone before it is used.','Review red calendar days, pending actual checkouts, and unresolved report delivery issues.','Deactivate users, stations, or contacts that are no longer in use. Preserve historical records; normal administration does not permanently delete them.']}
]};
