'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { onAuthStateChanged, signOut, type User } from 'firebase/auth';
import { ArrowLeft, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, Coffee, LayoutDashboard, LogOut, MapPin, Settings2, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SignIn } from '@/components/sign-in';
import { DutyCalendar } from '@/components/duty-calendar';
import { DayDetails } from '@/components/day-details';
import { AdminPanel } from '@/components/admin-panel';
import { Manual } from '@/components/manual';
import { BookOpen } from 'lucide-react';
import { CutoffSettings } from '@/components/cutoff-settings';
import { Avatar } from '@/components/avatar';
import { Modal } from '@/components/modal';
import { clientAuth } from '@/lib/firebase/client';
import { api } from '@/lib/api';
import { canCheckIn } from '@/lib/cutoff';
import { dateKey, TIME_ZONE, zuluLabel, dutyTimer, duration, timeLabel, totalForDay, overtimeForDays, TARGET_MS, type DutyData } from '@/lib/duty';
const logo='/kasas-limited-air-charters-original-logo%202%20(1).png';
const initials=(name:string)=>name.split(' ').filter(Boolean).map(n=>n[0]).slice(0,2).join('');
export default function Home(){
 const [restMessage,setRestMessage]=useState('');
 const [user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[data,setData]=useState<DutyData|null>(null),[teamData,setTeamData]=useState<DutyData|null>(null),[error,setError]=useState(''),[teamError,setTeamError]=useState(''),[month,setMonth]=useState(dateKey().slice(0,7)),[person,setPerson]=useState(''),[tab,setTab]=useState('My duty'),[reload,setReload]=useState(0),[loading,setLoading]=useState(false);
 const [now,setNow]=useState(Date.now()),[station,setStation]=useState(''),[notes,setNotes]=useState(''),[manualTime,setManualTime]=useState(''),[selected,setSelected]=useState<string|null>(null),[toast,setToast]=useState(''),[menu,setMenu]=useState(false),[profileOpen,setProfileOpen]=useState(false),[busy,setBusy]=useState(false),[celebration,setCelebration]=useState(false);
 const mutationLock=useRef(false); const cutoffSync=useRef(false); const refresh=()=>setReload(n=>n+1);
 useEffect(()=>onAuthStateChanged(clientAuth(),u=>{setUser(u);setAuthReady(true);setData(null);setTeamData(null);setPerson('');setSelected(null);setTab('My duty');setError('');setMenu(false);}),[]);
 useEffect(()=>{
   const syncClock=()=>setNow(Date.now());
   const resume=()=>{if(document.visibilityState==='visible'){syncClock();setReload(n=>n+1);}};
   const timer=setInterval(syncClock,1000);
   window.addEventListener('focus',syncClock);
   window.addEventListener('pageshow',resume);
   document.addEventListener('visibilitychange',resume);
   return()=>{clearInterval(timer);window.removeEventListener('focus',syncClock);window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume);};
 },[]);
 useEffect(()=>{if(!user)return;const timer=setInterval(refresh,30000);const focus=()=>refresh();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[user]);
 useEffect(()=>{if(!user)return;const controller=new AbortController();setLoading(true);api<DutyData>(`/api/duty?month=${month}`,undefined,controller.signal).then(d=>{setData(d);setError('');setStation(current=>d.active?.stationId||d.stations.find(s=>s.id===current)?.id||d.lastStationId||d.stations[0]?.id||'');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[user,month,reload,dateKey(now)]);
 useEffect(()=>{if(!user||!person){setTeamData(null);return;}const controller=new AbortController();setTeamError('');setTeamData(null);api<DutyData>(`/api/duty?month=${month}&uid=${encodeURIComponent(person)}`,undefined,controller.signal).then(setTeamData).catch(e=>{if(e.name!=='AbortError')setTeamError(e.message);});return()=>controller.abort();},[user,person,month,reload]);
 useEffect(()=>{
   if(!data?.active?.cutoffAt||now<data.active.cutoffAt||cutoffSync.current)return;
   cutoffSync.current=true;
   api('/api/cutoff',{action:'sync'}).then(()=>refresh()).catch(e=>setToast((e as Error).message)).finally(()=>{cutoffSync.current=false;});
 },[data?.active?.id,data?.active?.cutoffAt,Math.floor(now/30000)]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),7000);return()=>clearTimeout(timer);},[toast]);
 async function mutate(body:Record<string,unknown>){if(mutationLock.current)return false;mutationLock.current=true;setBusy(true);try{const result=await api<{message:string;delivery:string[]}>('/api/duty',{...body,requestId:crypto.randomUUID()});setRestMessage('');setToast(result.message+(result.delivery?.some(s=>s==='blocked')?' Email is saved for delivery once a manager and email service are configured.':result.delivery?.some(s=>s==='failed')?' Email delivery needs an administrator’s attention.':''));setManualTime('');setNotes('');refresh();if(body.action==='checkout')setCelebration(true);return true;}catch(e){setToast((e as Error).message);if(body.action==='checkin')setRestMessage((e as Error).message);refresh();return false;}finally{mutationLock.current=false;setBusy(false);}}
 if(!authReady)return <div className="app-loading" role="status"><Clock3 size={28}/><p>Opening your workspace…</p></div>;
 if(!user)return <SignIn/>;
 if(!data)return <div className="app-loading" role="status"><Image src={logo} alt="Kasas Limited" width={180} height={74}/><p>{error||'Loading your duty workspace…'}</p>{error&&<><Button onClick={refresh}>Try again</Button><Button variant="outline" onClick={()=>signOut(clientAuth())}>Sign out</Button></>}</div>;
 const zone=data.active?.timeZone||data.stations.find(s=>s.id===station)?.timeZone||data.timeZone||TIME_ZONE;
 const profile=data.profile, today=dateKey(now,zone), active=data.active, todayDay=data.todayDay?.date===dateKey(now,zone)?data.todayDay:data.days.find(d=>d.date===dateKey(now,zone));
 // The header always shows today's time, including while browsing a previous month.
 const currentMonth=month===today.slice(0,7);
 const cutoffPassed=!canCheckIn(now,profile.cutoffTime,zone);
 const {todayTotal:total,displayTotal}=dutyTimer(active,todayDay,now);
 const monthRecords=data.month===month?data.days:[];
 const hours=monthRecords.reduce((n,d)=>n+totalForDay(d),0),overtime=overtimeForDays(monthRecords);
 const canManage=profile.isLineManager||data.isAdmin;
 const viewing=person?teamData:data, viewProfile=person?data.team.find(p=>p.uid===person):profile;
 const pendingAuto=viewing?.pendingAutoCheckouts||[];
 const days=viewing?.days||[], selectedDay=days.find(d=>d.date===selected);
 const monthDays=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
 const isManual=tab==='User guide'||tab==='Admin manual';
 function switchTab(next:string){setTab(next);setPerson('');setSelected(null);}
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/" aria-label="Kasas Limited — DutyTime home"><Image className="company-logo" src={logo} alt="Kasas Limited" width={800} height={329} priority/></a><div className="workspace"><span className="company-mark">K</span><div><strong>{data.companyName}</strong><small>Your team workspace</small></div><ChevronDown size={15}/></div><p className="nav-label">WORKSPACE</p><nav><button className={tab==='My duty'?'nav-item current':'nav-item'} onClick={()=>switchTab('My duty')} title="Overview"><LayoutDashboard size={19}/>Overview<span className="nav-pill">Home</span></button>{canManage&&<button className={tab==='My line duty'?'nav-item current':'nav-item'} onClick={()=>switchTab('My line duty')} title="My team"><Users size={19}/>My team<span className="count">{data.team.length}</span></button>}<button className="nav-item" title="Duty history" onClick={()=>{switchTab('My duty');setTimeout(()=>document.getElementById('calendar')?.scrollIntoView({behavior:'smooth'}),50);}}><CalendarDays size={19}/>Duty history</button></nav>{data.isAdmin&&<><p className="nav-label management">MANAGEMENT</p><button className={tab==='Admin'?'nav-item current':'nav-item'} onClick={()=>switchTab('Admin')} title="Administration"><Settings2 size={19}/>Administration</button></>}<button className={tab==='User guide'?'nav-item current':'nav-item'} onClick={()=>switchTab('User guide')}><BookOpen size={19}/>User guide</button>{data.isAdmin&&<button className={tab==='Admin manual'?'nav-item current':'nav-item'} onClick={()=>switchTab('Admin manual')}><BookOpen size={19}/>Admin manual</button>}<div className="sidebar-bottom"><div className="help-card"><span className="help-icon"><Sparkles size={19}/></span><strong>A little balance goes a long way.</strong><p>Remember to take a break and make time for yourself.</p><span>You’ve got this <span className="sun">✳</span></span></div><div className="sidebar-footer"><span className="tiny-logo">◷</span>DutyTime<span>v1.0</span></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace<ChevronRight size={14}/><strong>{isManual?tab:tab==='Admin'?'Administration':'Overview'}</strong></div><a className="mobile-brand" href="/" aria-label="Kasas Limited — DutyTime home"><Image className="company-logo" src={logo} alt="Kasas Limited" width={800} height={329} priority/></a><div className="header-right"><span className="timezone">East Africa Time<span>EAT</span></span><button className="icon-button notification" aria-label="Report notifications" onClick={()=>setToast(data.reporting.blocked||data.reporting.failed?`${data.reporting.blocked} reports awaiting configuration; ${data.reporting.failed} deliveries need attention. Contact your administrator.`:data.reporting.queued?`${data.reporting.queued} reports are queued for delivery.`:'You’re all caught up. No report delivery issues.')}><Bell size={19}/>{!!(data.reporting.blocked||data.reporting.failed)&&<i/>}</button><div className="header-divider"/><button className="profile" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Avatar name={profile.name} photo={profile.photo}/><span><strong>{profile.name}</strong><small>{profile.department}</small></span><ChevronDown size={14}/></button>{menu&&<div className="profile-menu"><strong>{profile.name}</strong><small>{profile.email}</small><button onClick={()=>{setProfileOpen(true);setMenu(false);}}>My profile</button>{data.isAdmin&&<button onClick={()=>{switchTab('Admin');setMenu(false);}}>Administration</button>}<button onClick={()=>signOut(clientAuth()).catch(()=>setToast('Unable to sign out. Please try again.'))}><LogOut size={15}/>Sign out</button></div>}</div></header>
 <main><div className="page-heading"><div><div className="eyebrow"><span/>YOUR WORKDAY, IN VIEW</div><h1>{isManual?tab:tab==='Admin'?'A well-run team starts here':'A good day starts here'}<span>.</span></h1><p>Welcome back, {profile.firstName||profile.name}. Let’s make every hour count.</p></div><div className="date-label"><CalendarDays size={17}/>{new Date(now).toLocaleDateString('en-GB',{timeZone:zone,weekday:'short',day:'numeric',month:'short',year:'numeric'})}</div></div>{error&&<div className="connection-error" role="alert">{error}<button onClick={refresh}>Retry</button></div>}
 <section className="welcome-card"><div className="user-info"><Avatar name={profile.name} photo={profile.photo} large/><div><h2>{profile.name}<span className="employee-badge">{data.isAdmin?'Administrator':profile.isLineManager?'Line manager':'Team member'}</span></h2><p>{profile.department||'Department not assigned'}<span>·</span>{profile.position||'Position not assigned'}</p><div className="manager"><span className="mini-avatar"><Users size={11}/></span>Line manager{data.managers.length===1?'':'s'}<strong>{data.managers.map(m=>m.name).join(', ')||'Not assigned yet'}</strong></div></div></div><div className="today-clock"><div><span className={`status-dot ${active?'live':''}`}/>{active?(active.cutoffAt&&now>=active.cutoffAt?'Cutoff reached':'On duty'):'Ready when you are'}<span className="today-tag">{active?'CURRENT SESSION':'TODAY'}</span></div><div className={`clock-digits ${displayTotal>=360000000?'long-duration':''}`} aria-label={active?'Current session elapsed time':'Today’s duty time'}>{String(Math.floor(displayTotal/3600000)).padStart(2,'0')}<span>:</span>{String(Math.floor(displayTotal%3600000/60000)).padStart(2,'0')}<span>:</span><small>{String(Math.floor(displayTotal%60000/1000)).padStart(2,'0')}</small></div>{active&&<p className="session-start">Opened {active.date} at {timeLabel(active.start,zone)} ({zone}) · {zuluLabel(active.start)}</p>}<p>{total>TARGET_MS?'Today: 12-hour target exceeded':`Today: ${duration(total)} of 12h`}<span>{Math.min(100,Math.round(total/TARGET_MS*100))}%</span></p><div className="progress"><i style={{width:`${Math.min(100,total/TARGET_MS*100)}%`}}/></div>{total>TARGET_MS&&<div className="overtime-counter"><span>Overtime</span><strong>{duration(total-TARGET_MS)}</strong></div>}</div></section>
 <div className="tabs-row"><div className="tabs">{['My duty',...(canManage?['My line duty']:[]),...(data.isAdmin?['Admin']:[]),'User guide',...(data.isAdmin?['Admin manual']:[])].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>switchTab(t)}>{t==='User guide'||t==='Admin manual'?<BookOpen size={16}/>:t==='My duty'?<Clock3 size={16}/>:t==='Admin'?<Settings2 size={16}/>:<Users size={16}/>} {t}{t==='My line duty'&&<span>{data.team.length}</span>}</button>)}</div><span className="private-note"><ShieldCheck size={14}/>{loading?'Updating records…':'Your time, accurately recorded'}</span></div>
 {!isManual&&tab!=='Admin'&&pendingAuto.length>0&&<div className="pending-checkout-banner" role="status"><strong>Pending actual checkout</strong><p>{person?'This team member was':'You were'} automatically checked out. Record the actual time to confirm the hours.</p>{pendingAuto.map(item=><button key={item.id} onClick={()=>{setMonth(item.date.slice(0,7));setSelected(item.date);}}>Review {item.date}<ArrowRight size={14}/></button>)}</div>}
 {isManual?<Manual key={tab} kind={tab==='Admin manual'&&data.isAdmin?'admin':'user'}/>:tab==='Admin'?<AdminPanel notify={setToast} refresh={refresh}/>:tab==='My duty'?<><div className="duty-grid"><section className="card log-card"><div className="card-heading"><div className="title-icon"><Clock3 size={19}/></div><div><h2>Log duty</h2><p>Your next productive session starts here.</p></div><span className={`status-chip ${active?'on':''}`}>{active?'On duty':'Off duty'}</span></div><form onSubmit={e=>{e.preventDefault();void mutate(active?{action:'checkout',...(manualTime?{time:manualTime}:{})}:{action:'checkin',stationId:station,notes,...(manualTime?{time:manualTime}:{})});}}><div className="log-fields"><label>Work station<span>*</span><div className="select-wrap"><MapPin size={17}/><select required value={station} disabled={!!active||busy} onChange={e=>setStation(e.target.value)}><option value="">Select a station</option>{active&&!data.stations.some(s=>s.id===active.stationId)&&<option value={active.stationId}>{active.station}</option>}{data.stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><ChevronDown size={15}/></div></label><label>Notes<span className="optional">(optional)</span><textarea maxLength={2000} placeholder="Anything to note about your shift?" value={active?.notes??notes} disabled={!!active||busy} onChange={e=>setNotes(e.target.value)}/></label>{data.settings.allowManualTimes&&<label>{active?'Check-out':'Check-in'} time<input type="time" value={manualTime} disabled={busy} onChange={e=>setManualTime(e.target.value)}/><small>The time defaults to now. If you are logging it late, type the time you actually started or finished — that is what gets recorded, not the moment you pressed the button.</small></label>}</div>{restMessage&&<p className="connection-error" role="alert">{restMessage}</p>}<div className="check-actions"><Button type="submit" disabled={busy||!!error||!active&&(!station||cutoffPassed)||!!todayDay?.closed}>{busy?'Saving…':todayDay?.closed?'Day closed':active?'Check out':cutoffPassed?'Cutoff passed':'Check in'}<ArrowRight size={17}/></Button>{(todayDay?.sessions.length||0)>0&&!todayDay?.closed&&<Button type="button" variant="outline" disabled={busy} onClick={()=>mutate(active?{action:'checkout',closeDay:true,...(manualTime?{time:manualTime}:{})}:{action:'close'})}>Close for the day</Button>}</div></form><p className="cutoff-hint">Automatic checkout: {profile.cutoffTime||'19:00'} ({zone}). Check-in is blocked at or after this time. Automatic checkouts need your actual finish time.</p><div className="log-footer"><ShieldCheck size={14}/>{active?`Checked in ${active.date} at ${timeLabel(active.start,zone)} (${zone}) · ${zuluLabel(active.start)}`:'Your check-in time is recorded automatically.'}</div></section>
 <section className="card summary-card"><div className="summary-heading"><h2>{currentMonth?'This month':'Month summary'}</h2><span>{new Date(`${month}-01T12:00:00`).toLocaleDateString('en-GB',{month:'short',year:'numeric'})}</span></div><div className="summary-total"><span>{Math.floor(hours/3600000)}</span><small>h</small><span className="summary-minutes">{Math.floor(hours%3600000/60000)}<small>m</small></span></div><p className="total-caption">Approved & recorded duty hours</p><div className="mini-chart">{Array.from({length:monthDays},(_,i)=>{const day=monthRecords.find(d=>d.date===`${month}-${String(i+1).padStart(2,'0')}`);const value=totalForDay(day)/3600000;return <div key={i} title={`Day ${i+1}: ${value.toFixed(1)} hours`} className={value?'':'muted'} style={{height:`${value?Math.min(100,value*10):8}%`}}/>;})}</div><div className="chart-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div><div className="summary-stats"><div><span className="stat-icon green"><CalendarDays size={16}/></span><div><strong>{monthRecords.filter(d=>totalForDay(d)>0).length}<small> days</small></strong><p>Days worked</p></div></div><div><span className="stat-icon amber"><Clock3 size={16}/></span><div><strong>{duration(overtime)}</strong><p>Overtime</p></div></div></div><div className="balance-note"><Coffee size={16}/><span>Good work. Better balance.</span><span>✦</span></div></section></div><DutyCalendar month={month} setMonth={setMonth} days={monthRecords} active={active} choose={setSelected}/></>:person?<><div className="team-back"><Button variant="ghost" onClick={()=>{setPerson('');setSelected(null);}}><ArrowLeft size={16}/>Back to my team</Button><h2>{viewProfile?.name}</h2></div><CutoffSettings key={person} uid={person} value={viewProfile?.cutoffTime} notify={setToast} refresh={refresh}/>{teamError?<section className="card empty-state"><p>{teamError}</p><Button onClick={refresh}>Retry</Button></section>:teamData?<DutyCalendar title={`${viewProfile?.firstName||'Team member'}’s duty calendar`} month={month} setMonth={setMonth} days={teamData.days} active={teamData.active} choose={setSelected}/>:<section className="card empty-state" role="status">Loading duty records…</section>}</>:<section className="card team-card"><div className="calendar-header"><div><h2>My line duty</h2><p>Select a team member to set their lockout time, view their calendar, and review requests.</p></div><span className="status-chip">{data.team.length} members</span></div><div className="team-list">{data.team.length?data.team.map(p=><button key={p.uid} onClick={()=>setPerson(p.uid)}><Avatar name={p.name} photo={p.photo}/><div><strong>{p.name}</strong><small>{p.position||p.department}</small></div><span className="team-hours">View duty</span><ArrowUpRight size={17}/></button>):<div className="empty-state"><Users size={28}/><h3>Your team will appear here</h3><p>An administrator can assign you as a line manager in user settings.</p></div>}</div></section>}
 <footer className="page-footer"><span>© {new Date(now).getFullYear()} {data.companyName}. Every hour matters.</span><span>Made for a better workday<span className="footer-spark">✳</span></span></footer></main></div>
 {toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 {selected&&viewing&&viewing.month===month&&<DayDetails key={`${person}-${selected}`} date={selected} uid={person||profile.uid} name={viewProfile?.name||profile.name} day={selectedDay} stations={data.stations} manager={!!person&&canManage} own={!person} busy={busy} close={()=>setSelected(null)} mutate={mutate}/>}
 {profileOpen&&<Modal title="My profile" close={()=>setProfileOpen(false)}><div className="eyebrow">MY PROFILE</div><h2>{profile.name}</h2><p>{profile.email}</p><div className="session"><p>Department: {profile.department||'Not assigned'}</p><p>Position: {profile.position||'Not assigned'}</p><p>Line managers: {data.managers.map(m=>m.name).join(', ')||'Not assigned'}</p></div><p className="empty-copy">Contact your administrator to update your profile or manager assignments.</p></Modal>}
 {celebration&&<Modal title="Duty complete" close={()=>setCelebration(false)}><div className="celebration"><span className="celebration-icon"><Check size={34}/></span><div className="eyebrow">TIME WELL SPENT</div><h2>Good work, {profile.firstName}.</h2><p>You’ve finished your session.</p><strong>{duration(total)}</strong><p>recorded today{total>TARGET_MS?` · ${duration(total-TARGET_MS)} overtime`:''}</p><Button onClick={()=>setCelebration(false)}>Back to my day<ArrowRight size={16}/></Button></div></Modal>}
 </div>;
}
