'use client';
import { useId, useMemo, useState } from 'react';
import { z } from 'zod';
import { X, Search, Plus } from 'lucide-react';
import { api } from '@/lib/api';
import { Button } from './ui/button';
export type AlertContact={name:string;email:string;kind:'user'|'station'};
const normalize=(email:string)=>email.trim().toLowerCase();
export function AlertSettings({emails,contacts=[],notify,onSaved}:{emails:string[];contacts?:AlertContact[];notify:(s:string)=>void;onSaved?:(emails:string[])=>void}){
 const id=useId(),[selected,setSelected]=useState([...new Set(emails.map(normalize))]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const options=useMemo(()=>{const map=new Map<string,AlertContact>();for(const c of contacts){const email=normalize(c.email);if(z.email().safeParse(email).success){const old=map.get(email);map.set(email,{...c,email,name:old?`${old.name} / ${c.name}`:c.name});}}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name));},[contacts]);
 const matches=options.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.trim().toLowerCase()));
 const typed=normalize(query),validEmail=z.email().safeParse(typed).success;
 function toggle(email:string){setError('');setSelected(current=>current.includes(email)?current.filter(e=>e!==email):current.length<50?[...current,email]:current);}
 function add(){if(!validEmail){setError('Enter a valid email address to add it.');return;}if(!selected.includes(typed)){if(selected.length>=50){setError('You can select up to 50 additional recipients.');return;}setSelected([...selected,typed]);}setQuery('');setError('');}
 async function save(){const recipients=[...new Set([...selected,...(validEmail?[typed]:[])])];if(recipients.length>50){setError('You can select up to 50 additional recipients.');return;}setBusy(true);setError('');try{const result=await api<{message:string}>('/api/admin',{action:'alertRecipients',alertEmails:recipients});setSelected(recipients);setQuery('');onSaved?.(recipients);notify(result.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="alert-settings" onSubmit={e=>{e.preventDefault();void save();}}><h3>Duty & rest alerts</h3><p>Assigned line managers and the selected stations’ Maintenance and Operations contacts receive alerts automatically. Select additional users, station contacts, or add an email address for both overtime and insufficient-rest alerts.</p><div className="recipient-chips" aria-label="Selected alert recipients">{selected.map(email=><span className="recipient-chip" key={email}><span><strong>{options.find(c=>c.email===email)?.name||email}</strong>{options.some(c=>c.email===email)&&<small>{email}</small>}</span><button type="button" disabled={busy} aria-label={`Remove ${email}`} onClick={()=>toggle(email)}><X size={14}/></button></span>)}</div><label htmlFor={id}>Search alert recipients</label><div className="recipient-search"><Search size={17}/><input id={id} type="search" autoComplete="off" placeholder="Name, station, department, or email" value={query} disabled={busy} aria-describedby={`${id}-help`} onChange={e=>{setQuery(e.target.value);setError('');}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}}/></div><small id={`${id}-help`}>Select multiple matches. For a new email, type it and press Enter or Add email.</small>{validEmail&&!selected.includes(typed)&&<Button type="button" variant="outline" disabled={busy||selected.length>=50} onClick={add}><Plus size={15}/>Add email: {typed}</Button>}<div className="recipient-results" role="group" aria-label="Matching alert contacts">{matches.slice(0,30).map(c=><label className="recipient-option" key={c.email}><input type="checkbox" disabled={busy||selected.length>=50&&!selected.includes(c.email)} checked={selected.includes(c.email)} onChange={()=>toggle(c.email)}/><span><strong>{c.name}</strong><small>{c.kind==='station'?'Station contact':'User'} · {c.email}</small></span></label>)}{!matches.length&&<p>{validEmail?'Add this email to your recipients.':'No matching contacts. Search another name or enter an email address.'}</p>}</div><small aria-live="polite">{selected.length} of 50 recipients selected{matches.length>30?' · Showing the first 30 matches; type to narrow the list.':''}</small>{error&&<p role="alert" className="form-message">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save alert recipients'}</Button></form>;
}
