'use client';
import { useEffect,useState } from 'react';
import { Mail, Phone, Pencil, Power, Users } from 'lucide-react';
import { api } from '@/lib/api';
import { type StationContact } from '@/lib/duty';
import { Button } from './ui/button';
export function StationContacts({stationId,notify,onChanged}:{stationId:string;notify:(s:string)=>void;onChanged?:()=>void}){
 const [contacts,setContacts]=useState<StationContact[]>([]),[form,setForm]=useState({id:'',name:'',email:'',phone:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{setContacts((await api<{contacts:StationContact[]}>(`/api/station-contacts?stationId=${encodeURIComponent(stationId)}`)).contacts);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[stationId]);
 async function save(toggle=false,id=form.id){setBusy(true);try{const result=await api<{message:string}>('/api/station-contacts',toggle?{action:'setActive',stationId,id,active:contacts.find(c=>c.id===id)?.active===false}:{action:'save',stationId,...form,id:form.id||undefined});notify(result.message);setForm({id:'',name:'',email:'',phone:''});await load();onChanged?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="station-contacts"><h3>Station contacts</h3><p>Maintenance and Operations contacts automatically receive duty and rest alerts for this station. You can also add other contact types.</p>{error&&<p role="alert">{error}</p>}<div className="station-contact-list">{contacts.map(c=><article className={`station-contact-card ${form.id===c.id?'is-editing':''} ${c.active===false?'inactive-contact':''}`} key={c.id}><div className="station-contact-avatar" aria-hidden="true">{c.name.trim().split(/\s+/).map(word=>word[0]).slice(0,2).join('').toUpperCase()}</div><div className="station-contact-info"><h4>{c.name} {c.active===false&&<span className="status-chip">Inactive</span>}</h4><div className="station-contact-details">{c.email&&<a href={`mailto:${c.email}`}><Mail size={14}/><span>{c.email}</span></a>}{c.phone&&<a href={`tel:${c.phone}`}><Phone size={14}/><span>{c.phone}</span></a>}</div></div><div className="station-contact-actions"><button type="button" disabled={busy} aria-label={`Edit ${c.name}`} title="Edit contact" onClick={()=>{setForm(c);document.getElementById(`contact-form-${stationId}`)?.scrollIntoView({behavior:'smooth',block:'nearest'});}}><Pencil size={16}/><span>Edit</span></button><button type="button" className="delete-contact" disabled={busy} aria-label={`${c.active===false?'Reactivate':'Deactivate'} ${c.name}`} title={c.active===false?'Reactivate contact':'Deactivate contact'} onClick={()=>void save(true,c.id)}><Power size={16}/><span>{c.active===false?'Reactivate':'Deactivate'}</span></button></div></article>)}{!contacts.length&&!error&&<div className="station-contacts-empty"><Users size={24}/><div><strong>No contacts yet</strong><p>Add your station’s first department contact below.</p></div></div>}</div><form id={`contact-form-${stationId}`} className="station-contact-form" onSubmit={e=>{e.preventDefault();void save();}}><h4>{form.id?'Edit contact':'Add contact'}</h4><label>Contact name / department<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Maintenance"/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><Button disabled={busy||!form.name||!(form.email||form.phone)} type="submit">Save contact</Button>{form.id&&<Button type="button" variant="ghost" onClick={()=>setForm({id:'',name:'',email:'',phone:''})}>Cancel edit</Button>}</form></section>;
}
