export type ManualSection={id:string;title:string;steps:string[];note?:string};
export type ManualContent={title:string;intro:string;sections:ManualSection[]};
export const userManual:ManualContent={title:'User guide',intro:'From your first sign-in to a complete duty record. All duty times follow the station you select.',sections:[
{id:'sign-in',title:'1. Get access and sign in',steps:['Ask your administrator to enable DutyTime access, confirm your email address, and assign your line manager. There is no self-registration screen.','Open DutyTime and enter your existing Kasas email address and password, then select Sign in.','If you forgot your password, choose Forgot your password?, enter your account email, and follow the emailed reset link. Check your spam folder too.','If sign-in works but access is denied, ask the administrator to check your DutyTime membership and company.'],note:'Use the same account you use for the other connected Kasas apps.'},
{id:'check-in',title:'2. Start your duty',steps:['In My duty, select the work station where you are working. Check that its time zone is correct; report mistakes to your administrator.','Add any useful notes, then choose Check in. The start time is saved and the timer continues even if you close the browser.','If your administrator enabled manual times, enter the actual local start time when logging late. Future times and overlapping sessions are rejected.'],note:'Only one session can be open. Check-in is blocked at or after the station-local cutoff: 7pm by default, or your manager’s override.'},
{id:'rest',title:'3. Observe the rest and duty limits',steps:['Before the next duty day, take at least eight hours of rest after your latest checkout. For example, a 10pm checkout allows the next day’s check-in from 6am.','An earlier next-day attempt is denied and shows an explanation. An alert goes to your line managers, configured additional recipients, and Maintenance/Operations at the station selected for that attempt.','Short breaks and repeat sessions within the same local duty day are allowed.','If total daily duty exceeds 12 hours, the calendar day turns red and an alert is sent. Work can continue until the separate daily cutoff.']},
{id:'checkout',title:'4. Check out and take breaks',steps:['Choose Check out when a session ends. Its hours are added to your daily total and a report is queued for your line managers.','To return after a same-day break, check in again before your cutoff. Break time does not count as duty.','Choose Close for the day only when you are finished. This prevents further check-ins for that date; ask your manager if the record needs correction.']},
{id:'automatic',title:'5. Resolve an automatic checkout',steps:['At your cutoff, the system checks you out automatically. The user and line managers receive an email and the record shows Pending actual checkout.','Open the pending-day banner or select that day in your calendar. Choose Set actual checkout.','Enter the actual local finish date and time, add a reason, and confirm. Your line manager can also make this correction.','Confirmed hours are recalculated and corrected emails are queued. Resolve the previous day’s pending checkout before starting a new day so rest can be verified.'],note:'Provisional automatic-checkout hours do not count toward confirmed totals until the actual finish time is recorded.'},
{id:'history',title:'6. Review history or request a missed entry',steps:['Open Duty history or your calendar and select a date to see individual sessions, station-local times, Zulu times, and corrections.','For a past date with no duty record, select the station, enter start and finish times, and give a reason for the missed entry. Submit Request approval.','Your assigned line manager reviews the request. Pending or rejected requests do not count as confirmed hours.','Use Export report on the calendar to download a CSV for the selected month.']},
{id:'help',title:'7. Get help and sign out',steps:['Contact your line manager for cutoff changes, missed-entry reviews, and corrections. Contact an administrator for account access, missing stations, incorrect time zones, or email delivery problems.','Open your profile menu at the top and choose Sign out when finished, especially on a shared device.']}
]};
